name: route_auth_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.3.1
  code_builder: ^4.2.0
  shelf_router: ^1.1.3
  route_auth:
    git:
      url: https://github.com/masewo/route_auth.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
